services:
  test_app:
    build:
      context: .
    container_name: test_app
    command: uvicorn app.main:main_app --host 0.0.0.0 --port 7000 --reload
    ports:
      - "7000:7000"
    depends_on:
      - test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: "5432"
      PROJECT_NAME: test_Mini_CRM
      POSTGRES_SERVER: test_db
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - ./:/app

  

  test_db:
    image: postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      retries: 5