"""Add ON DELETE CASCADE to profile.user_id

Revision ID: c6a823ca01c0
Revises: 5ad856bcecff
Create Date: 2025-07-02 09:33:51.216084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6a823ca01c0"
down_revision: Union[str, Sequence[str], None] = "5ad856bcecff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deals", "manager_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("deals_manager_id_fkey"), "deals", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "deals", "users", ["manager_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        op.f("profiles_user_id_fkey"), "profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "profiles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "tasks", "manager_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("tasks_manager_id_fkey"), "tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "tasks", "users", ["manager_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(
        op.f("users_projects_project_id_fkey"),
        "users_projects",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("users_projects_user_id_fkey"),
        "users_projects",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "users_projects",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "users_projects",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_projects", type_="foreignkey")
    op.drop_constraint(None, "users_projects", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_projects_user_id_fkey"),
        "users_projects",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("users_projects_project_id_fkey"),
        "users_projects",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_manager_id_fkey"), "tasks", "users", ["manager_id"], ["id"]
    )
    op.alter_column(
        "tasks", "manager_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(None, "profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("profiles_user_id_fkey"), "profiles", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "deals", type_="foreignkey")
    op.create_foreign_key(
        op.f("deals_manager_id_fkey"), "deals", "users", ["manager_id"], ["id"]
    )
    op.alter_column(
        "deals", "manager_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
