"""added number field in Project model

Revision ID: 3e3759c9d067
Revises: 8ca813b9af72
Create Date: 2025-10-13 12:28:02.418337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e3759c9d067"
down_revision: Union[str, Sequence[str], None] = "8ca813b9af72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("number", sa.Integer(), nullable=False)
    )
    op.add_column(
        "projects",
        sa.Column(
            "type",
            sa.Enum(
                "web_site",
                "mobile_app",
                "desktop_app",
                "telegram_bot",
                name="projectsname",
            ),
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "projects", ["number"])
    op.drop_column("projects", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "name",
            postgresql.ENUM(
                "web_site",
                "mobile_app",
                "desktop_app",
                "telegram_bot",
                name="projectsname",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "projects", type_="unique")
    op.drop_column("projects", "type")
    op.drop_column("projects", "number")
    # ### end Alembic commands ###
