"""client 13 digits

Revision ID: 5ad856bcecff
Revises: 0894480ced35
Create Date: 2025-06-28 16:33:40.292462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ad856bcecff"
down_revision: Union[str, Sequence[str], None] = "0894480ced35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "phone",
        existing_type=sa.VARCHAR(length=12),
        type_=sa.String(length=13),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clients",
        "phone",
        existing_type=sa.String(length=13),
        type_=sa.VARCHAR(length=12),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
