"""add relationship for task

Revision ID: 0437fb8c830b
Revises: 6a827ea87c2f
Create Date: 2025-06-23 17:53:23.263687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0437fb8c830b"
down_revision: Union[str, Sequence[str], None] = "6a827ea87c2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("manager_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "tasks", "users", ["manager_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "manager_id")
    # ### end Alembic commands ###
